services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      TZ: Europe/Warsaw
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - custom_network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      TZ: Europe/Warsaw
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - custom_network

  n8n:
    image: n8nio/n8n:1.89.2
    restart: always
    ports:
      - "5678:5678"
    environment:
      - TZ=Europe/Warsaw
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      - custom_network

  telethon-listener:
    image: q910705/telegram-client:c1f692c02e3dd05bfff1264e92c46013dbcb52d3
    restart: always
    ports:
      - "8080:8080"
      - "8765:8765"
    environment:
      - TZ=Europe/Warsaw
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE=${TELEGRAM_PHONE}
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/telegram
      - TELEGRAM_SESSION_DIR=/data
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - IGNORED_SENDERS=PinkPunkTradingBot,Tom_Trader81,Witu
    volumes:
      - telethon_session:/data
    depends_on:
      - n8n
      - postgres
    networks:
      - custom_network

  bybit-trade-zarabiara:
    image: q910705/bybit-trade:c4a3d33511ba425e2656f27601ef2eb396cee8ae
    restart: always
    ports:
      - "8888:8888"
    environment:
      - TZ=Europe/Warsaw
      - BYBIT_API_KEY=${BYBIT_API_KEY_TELEGRAM}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET_TELEGRAM}
    networks:
      - custom_network

  bybit-trade:
    image: q910705/bybit-trade:c4a3d33511ba425e2656f27601ef2eb396cee8ae
    restart: always
    ports:
      - "9999:9999"
    environment:
      - TZ=Europe/Warsaw
      - BYBIT_API_KEY=${BYBIT_API_KEY_BITCOIN_NOTIFIER}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET_BITCOIN_NOTIFIER}
      - SERVER_PORT=9999
      - RETRACEMENT_DIVIDER=4
    networks:
      - custom_network

  bitcoin-notifier:
    image: q910705/bitcoin-notifier:c921251862bb6c98a10746708a47abf78f470a48
    container_name: bitcoin-notifier
    restart: always
    volumes:
      - ./logs:/logs
    environment:
      - TZ=Europe/Warsaw
      - INDICATOR_LOG_PATH=/logs/indicator_levels.log
    env_file:
      - .env
    networks:
      - custom_network

volumes:
  n8n_postgres_data:
  n8n_data:
  telethon_session:
  pgadmin_data:

networks:
  custom_network:
    driver: bridge
